### ISSUE TITLE
Error creating .hyper file

### ISSUE THREAD

**Issue by jacobhjkim** [danielgp/tableau-hyper-management#1]
**Describe the bug**

**To Reproduce**
1. Example CSV
```csv
user_id,target_level,is_payer,days_for_target_level
abcd,11,false,0.0
abcd,12,false,1.0
abcd,13,false,3.0
abcd,14,false,506.0
abcd,15,false,506.0
abcd,16,false,506.0
abcd,17,false,506.0
xyz,2,false,0.0
xyz,3,false,0.0
```

2. `python3 tableau-hyper-management/main.py --input-file test.csv --csv-field-separator , --output-file test.hyper`

**Expected behavior**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-Feb-20 11:40:53.865085 UTC - Input file is test.csv
2020-Feb-20 11:40:53.865116 UTC - CSV field separator is ,
2020-Feb-20 11:40:53.865129 UTC - Unique values to analyze is limited to 200
2020-Feb-20 11:40:53.865140 UTC - Output file is test.hyper
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "tableau-hyper-management/main.py", line 45, in <module>
    parameters_interpreted)
  File "/home/ubuntu/tableau-hyper-management/tableau_hyper_management/TypeDetermination.py", line 84, in fn_detect_csv_structure
    in_prmtrs.verbose)
IndexError: list assignment index out of range

**Desktop (please complete the following information):**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
Tested on `c5.4xlarge` AWS EC2 instance

**Additional context**
I am not sure why this is giving me a list index out of bounds error. Any help would be appreciated.

**Comment by danielgp** [comment]
I just found the problem which seems to be a Boolean type that needs to be considered, will issue a fix right away and let you know once release.
Thank you very much for raising this out!

**Comment by danielgp** [comment]
this resolved and new version released, please recheck and let me know

**Comment by jacobhjkim** [comment]
Thanks! I have tested it and it seems like the issue is resolved.
